[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
#   '@chainlink/contracts/src/=/lib/chainlink-brownie-contracts/contracts/src/',
#   '@chainlink/=lib/chainlink-brownie-contracts/contracts/',
  '@chainlink/=lib/chainlink-brownie-contracts/contracts/',


]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
